version: '3.1'
services:
  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  api:
    build: .
    container_name: api
    environment:
      SPRING_PROFILES_ACTIVE: local
    ports:
      - 8081:8081
      - 5005:5005 # debug port
    depends_on:
      - postgres
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  postgres_data:
    driver: local