version: '3.1'
services:
  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  api:
    build: server/api/.
    container_name: api
    restart: always
    depends_on:
      - rabbitmq
      - keycloak
      - postgres
    networks:
      - backend
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server/nginx/html/index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - 80:80
    depends_on:
      - keycloak
      - api
    networks:
      backend:
        aliases:
          - keycloak.pokerapp.local
          - api.pokerapp.local
networks:
  backend:
    driver: bridge
volumes:
  postgres_data:
    driver: local