version: '2.4'
services:
  rabbitmq:
    build: server/rabbitmq/.
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    networks:
      - backend
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KK_TO_RMQ_URL: rabbitmq
      KK_TO_RMQ_PORT: 5672
      KK_TO_RMQ_VHOST: /
      KK_TO_RMQ_EXCHANGE: amq.topic
      KK_TO_RMQ_USERNAME: admin
      KK_TO_RMQ_PASSWORD: admin
      KK_TO_RMQ_USE_TLS: false
    depends_on:
      - rabbitmq
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./server/keycloak/keycloak-realm.json:/opt/keycloak/data/import/realm.json
      - ./server/keycloak/keycloak-to-rabbit-3.0.2.jar:/opt/keycloak/providers/keycloak-to-rabbit-3.0.2.jar
    networks:
      - backend
  api:
    build: server/api/.
    container_name: api
    restart: always
    depends_on:
      - rabbitmq
      - keycloak
    networks:
      - backend
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - keycloak
      - api
    networks:
      backend:
        aliases:
          - keycloak.pokerapp.local
          - rabbitmq.pokerapp.local
          - api.pokerapp.local
networks:
  backend:
    name: backend
    driver: bridge