version: '3.1'
services:
  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - ./server/postgres/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql:ro
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  rabbitmq:
    build: server/rabbitmq/.
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    networks:
      - backend
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KK_TO_RMQ_URL: rabbitmq
      KK_TO_RMQ_PORT: 5672
      KK_TO_RMQ_VHOST: /
      KK_TO_RMQ_EXCHANGE: amq.topic
      KK_TO_RMQ_USERNAME: admin
      KK_TO_RMQ_PASSWORD: admin
      KK_TO_RMQ_USE_TLS: false
    depends_on:
      - rabbitmq
      - postgres
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./server/keycloak/keycloak-realm.json:/opt/keycloak/data/import/realm.json
      - ./server/keycloak/keycloak-to-rabbit-3.0.2.jar:/opt/keycloak/providers/keycloak-to-rabbit-3.0.2.jar
    networks:
      - backend
  api:
    build: server/api/.
    container_name: api
    restart: always
    depends_on:
      - rabbitmq
      - keycloak
      - postgres
    networks:
      - backend
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - keycloak
      - api
    networks:
      backend:
        aliases:
          - keycloak.pokerapp.local
          - api.pokerapp.local
networks:
  backend:
    driver: bridge
volumes:
  postgres_data:
    driver: local