version: '3.1'
services:
  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  api:
    build: server/local/api/.
    container_name: api
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      - postgres
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  postgres_data:
    driver: local