version: '2.4'
services:
  rabbitmq:
    image: itzg/rabbitmq-stomp
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    networks:
      - backend
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - 8180:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/keycloak-realm.json:/opt/keycloak/data/import/realm.json
    networks:
      - backend
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
      - keycloak
    networks:
      - backend
networks:
  backend:
    name: backend
    driver: bridge