version: '2.4'
services:
  rabbitmq:
    image: itzg/rabbitmq-stomp
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    networks:
      - backend
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/keycloak-realm.json:/opt/keycloak/data/import/realm.json
    networks:
      - backend
  app:
    build: .
    container_name: app
    restart: always
    depends_on:
      - rabbitmq
      - keycloak
    networks:
      - backend
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/html:/etc/nginx/html:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - keycloak
      - app
    networks:
      backend:
        aliases:
          - keycloak.pokerapp.local
          - api.pokerapp.local
networks:
  backend:
    name: backend
    driver: bridge