spring:
  application:
    name: poker-game-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.pokerapp.local/realms/poker-game-realm
          jwk-set-uri: http://keycloak.pokerapp.local/realms/poker-game-realm/protocol/openid-connect/certs
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

jwt:
  auth:
    converter:
      resource-id: poker-game-keycloak-client
      principal-attribute: preferred_username

server:
  port:
    8081

logging:
  level:
    org.springframework.security: DEBUG

app:
  cors:
    allow-origins: http://localhost:63342
    allow-credentials: true
