keycloak:
  server-url: http://keycloak.twbdev.site
  realm: poker-app
  client-id: poker-game-api-client
  username: admin
  password: admin
  admin-group-id: 900d795d-15e2-407a-8952-d16ca8aa2c6b
  user-group-id: 1ecf1db5-4a66-48ec-8064-47e59dd0a4f1
  connection-pool-size: 10
spring:
  profiles:
    active: local
  application:
    name: poker-app-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
  datasource:
    url: jdbc:postgresql://postgres:5432/db
    driver-class-name: org.postgresql.Driver
    username: root
    password: password
  jpa:
    open-in-view: false
  hibernate:
    dll-auto: none
  liquibase:
    change-log: classpath:liquibase/master.xml
  jackson:
    serialization:
      fail_on_empty_beans: false
jwt:
  auth:
    converter:
      resource-id: ${keycloak.client-id}
      principal-attribute: preferred_username
server:
  port:
    8081
#logging:
#  level:
#    org.springframework.security: DEBUG
