name: 'nginx'
services:
  nginx-base:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./conf.d/app_locations.inc:/etc/nginx/conf.d/app_locations.inc:ro
      - ./conf.d/tailscale.conf:/etc/nginx/conf.d/tailscale.conf:ro
      - ./conf.d/proxy_params.conf:/etc/nginx/conf.d/proxy_params.conf:ro
      - ./html:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://127.0.0.1/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
