name: 'tailscale'
services:
  tailscale-base:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: poker-app
    volumes:
      - tailscale_data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    env_file:
      - ../env/.secrets.env
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TS_HOSTNAME=poker-app
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
      - TS_ADVERTISE_ROUTES=
      - TS_EPHEMERAL=false
      - TS_EXTRA_ARGS=--accept-routes --shields-up=false
    restart: unless-stopped
    healthcheck: # This check waits until tailscale can resolve its own hostname to an IP.
      test: ["CMD-SHELL", "tailscale ip -4 poker-app | grep -E '^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$$' > /dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
